spring:
  application:
    name: 'Financial-Tool'
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'postgres'
    driverClassName: 'org.postgresql.Driver'
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
