CREATE TABLE EXPENSE_MOVEMENT
(
    ID               BIGINT not null ,
--     ACCOUNT_MOVEMENT BIGINT    NOT NULL,
    EXPENSE_CATEGORY BIGINT    NOT NULL,
    PAYMENT_TYPE     BIGINT    NOT NULL,
    CREATED_AT       TIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP NOT NULL,
    FOREIGN KEY (ID) REFERENCES ACCOUNT_MOVEMENT (ID),
--     FOREIGN KEY (ACCOUNT_MOVEMENT) REFERENCES ACCOUNT_MOVEMENT (ID),
    FOREIGN KEY (EXPENSE_CATEGORY) REFERENCES EXPENSE_CATEGORY (ID),
    FOREIGN KEY (PAYMENT_TYPE) REFERENCES PAYMENT_TYPE (ID),
    UNIQUE (ID)
);