INSERT INTO EXPENSE_CATEGORY (CATEGORY_NAME, CREATED_AT, UPDATED_AT)
VALUES
    ('Aluguel', now(), now()),
    ('Condomínio', now(), now()),
    ('Manutenção', now(), now()),
    ('Mercado', now(), now()),
    ('Refeição Fora', now(), now()),
    ('Esportes', now(), now()),
    ('Jogos', now(), now()),
    ('Água', now(), now()),
    ('Luz', now(), now()),
    ('Telefone', now(), now()),
    ('TV/Internet/Telefone', now(), now()),
    ('Carro', now(), now()),
    ('Estacionamento', now(), now()),
    ('Combustível', now(), now()),
    ('Transporte público', now(), now()),
    ('Hotel', now(), now()),
    ('Seguro', now(), now()),
    ('Despesas Médicas', now(), now()),
    ('Roupa', now(), now()),
    ('Educação', now(), now()),
    ('Fatura cartão', now(), now()),
    ('Outros', now(), now());