CREATE TABLE PERSON_EXPENSE_GROUP (
  PERSON BIGINT,
  EXPENSE_GROUP BIGINT,
  PRIMARY KEY (PERSON, EXPENSE_GROUP),
  FOREIGN KEY (PERSON) REFERENCES PERSON (ID),
  FOREIGN KEY (EXPENSE_GROUP) REFERENCES EXPENSE_GROUP (ID)
);